module.exports = {
	UserModal: require("./user"),
	PostModal: require("./post"),
	PostLikeModal: require("./postLike"),
	FriendshipModal: require("./friendship"),
	CommentModal: require("./comment"),
	ConversationModal: require("./conversation"),
	MessageModal: require("./message"),
	MessageStatusModal: require("./messageStatus"),
	MediaModal: require("./media"),
	SharedPostModal: require("./sharedPost"),
	GroupModal: require("./group"),
	GroupMemberModal: require("./groupMember"),
	StoryModal: require("./story"),
	StoryViewModal: require("./storyView"),
};
